package com.bitwarden.server.enums;

public enum DeviceType {
    ANDROID,
    IOS,
    CHROME_EXTENSION,
    FIREFOX_EXTENSION,
    OPERA_EXTENSION,
    EDGE_EXTENSION,
    WINDOWS_DESKTOP,
    MAC_OS_DESKTOP,
    LINUX_DESKTOP,
    CHROME_BROWSER,
    FIREFOX_BROWSER,
    OPERA_BROWSER,
    EDGE_BROWSER,
    IE_BROWSER,
    UNKNOWN_BROWSER,
    ANDROID_AMAZON,
    UWP,
    SAFARI_BROWSER,
    VIVALDI_BROWSER,
    VIVALDI_EXTENSION,
    SAFARI_EXTENSION,
    SDK
}
